# numpy = numerical Python

In [1]:
import numpy as np

# array = lista cu toate elementele de acelasi tip

In [3]:
np.array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [5]:
arr = np.array([0, 1, 2, 3, 4])
type(arr), arr.dtype

(numpy.ndarray, dtype('int64'))

In [6]:
arr = np.array([0, 1, 2, 3.0, 4])
type(arr), arr.dtype

(numpy.ndarray, dtype('float64'))

In [7]:
arr = np.arange(10)
arr, type(arr), arr.dtype

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray, dtype('int64'))

In [8]:
arr = np.arange(10, 20)
arr, type(arr), arr.dtype

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 numpy.ndarray,
 dtype('int64'))

In [9]:
arr = np.arange(10, 20, 2)
arr, type(arr), arr.dtype

(array([10, 12, 14, 16, 18]), numpy.ndarray, dtype('int64'))

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones(10) * 2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [13]:
print([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.] * 2)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [14]:
print([1., 1.] * 2)

[1.0, 1.0, 1.0, 1.0]


In [15]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

In [16]:
np.array([1, 2, 3]) ** 2

array([1, 4, 9])

In [17]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
np.arange(100) % 7

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
       1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2,
       3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3,
       4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1])

In [19]:
np.arange(100) % 7 == 0

array([ True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False])

In [ ]:
np.arange(100) [np.arange(100) % 7 == 0]

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [24]:
np.arange(100).reshape(10, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [25]:
np.arange(100).reshape(25, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [26]:
np.arange(100).reshape(4, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [64]:
np.random.randint(1, 100, 3)

array([ 2, 61,  4], dtype=int32)

In [81]:
np.random.randint(1, 100, (3, 3))

array([[64, 13, 45],
       [94, 65, 38],
       [19, 15, 52]], dtype=int32)

In [97]:
np.random.random(3)

array([0.31803137, 0.12658948, 0.56854371])

In [99]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [100]:
array = np.random.randint(21, 23, 50)
array

array([21, 22, 21, 22, 21, 22, 21, 21, 21, 21, 21, 21, 21, 21, 22, 21, 22,
       21, 22, 21, 21, 21, 21, 21, 21, 21, 22, 22, 21, 22, 22, 22, 22, 21,
       21, 22, 21, 21, 21, 21, 21, 22, 21, 21, 21, 22, 21, 21, 22, 21],
      dtype=int32)

In [101]:
array [array == 22]

array([22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22],
      dtype=int32)

In [139]:
array = np.random.randint(2, 100, 50)
array

array([15, 89, 55, 29,  4, 28, 98, 13, 82, 78, 34,  5, 30,  3, 88, 94, 82,
       70, 55, 28, 34, 99, 68, 34, 82, 49, 11, 91, 51,  7, 99, 33, 10, 39,
       64, 78, 39, 86, 32, 20, 58, 58, 20, 26, 95, 72, 88, 65, 71, 95],
      dtype=int32)

In [141]:
array.max(), array.argmax()

(np.int32(99), np.int64(21))